"""
Central configuration for the ADHD Curvelet-MRI analysis pipeline.

All file system paths are defined here and can be overridden through
environment variables, so no absolute paths are hard-coded in the
analysis scripts. Set DATA_ROOT to the directory that contains the
project data, or export the individual variables before running.

Example:
    export DATA_ROOT=/path/to/ADHD2026
    python src/experiments/exp2_supervised.py
"""

import os

# ---------------------------------------------------------------------------
# Root directory containing all project data (CSV feature files, phenotypics,
# QC outputs). Override with:  export DATA_ROOT=/your/path
# ---------------------------------------------------------------------------
DATA_ROOT = os.environ.get("DATA_ROOT", "./data")

# ---------------------------------------------------------------------------
# Curvelet feature CSVs
#   FEATURES_RAW       : region_index, dx_group, 243 Curvelet coefficients
#                        (used by the main experiments 1-5 and LOSO)
#   FEATURES_COMPLETED : adds subject_id, site_id, sex, age columns
#                        (used by the sensitivity analyses)
# ---------------------------------------------------------------------------
def features_raw(subset: str) -> str:
    """subset in {'comparison_sample' (201), '649_subjects', '875_subjects'}"""
    return os.path.join(DATA_ROOT, subset, "curvelet_data_adhd_raw_4scales.csv")

FEATURES_COMPLETED = os.environ.get(
    "FEATURES_COMPLETED",
    os.path.join(DATA_ROOT, "875_subjects",
                 "curvelet_data_adhd_completed_axial_4scales.csv"),
)

# ---------------------------------------------------------------------------
# Phenotypic and auxiliary tables
# ---------------------------------------------------------------------------
PHENO_ADHD200   = os.environ.get("PHENO_ADHD200",
                                 os.path.join(DATA_ROOT, "ADHD200phenotypics.csv"))
PARTICIPANTS_WMR = os.environ.get("PARTICIPANTS_WMR",
                                  os.path.join(DATA_ROOT, "participantsWMR.csv"))
NAIVE_IDS       = os.environ.get("NAIVE_IDS",
                                 os.path.join(DATA_ROOT, "medication_naive_adhdc_ids.csv"))

# QC intermediate outputs (generated by scripts in src/quality_control/)
EULER_ADHD200   = os.environ.get("EULER_ADHD200",
                                 os.path.join(DATA_ROOT, "euler_numbers.csv"))
EULER_WMR       = os.environ.get("EULER_WMR",
                                 os.path.join(DATA_ROOT, "euler_wmr.csv"))
PSNR_SSIM       = os.environ.get("PSNR_SSIM",
                                 os.path.join(DATA_ROOT, "psnr_ssim.csv"))

# ---------------------------------------------------------------------------
# Raw FreeSurfer recon-all output trees (needed only to recompute QC metrics)
# ---------------------------------------------------------------------------
FS_INCLUDED = os.environ.get("FS_INCLUDED", os.path.join(DATA_ROOT, "freesurfer", "Preprocessed"))
FS_EXCLUDED = os.environ.get("FS_EXCLUDED", os.path.join(DATA_ROOT, "freesurfer", "Noise_cases"))
FS_WMR      = os.environ.get("FS_WMR",      os.path.join(DATA_ROOT, "freesurfer", "WMR_ADHD"))
FREESURFER_HOME = os.environ.get("FREESURFER_HOME", "/usr/local/freesurfer")
MNI_TEMPLATE = os.environ.get(
    "MNI_TEMPLATE",
    os.path.join("$FREESURFER_HOME", "average",
                 "Choi_JNeurophysiol12_MNI152",
                 "FSL_MNI152_FreeSurferConformed_1mm.nii.gz"),
)

# ---------------------------------------------------------------------------
# Output directory for results
# ---------------------------------------------------------------------------
RESULTS_ROOT = os.environ.get("RESULTS_ROOT", "./results")

# ---------------------------------------------------------------------------
# Global analysis parameters (identical across all experiments)
# ---------------------------------------------------------------------------
RANDOM_SEED = 70
N_BOOTSTRAP = 500
N_PERMUT    = 1000
N_JOBS      = -3
